# 2. Handle the Arithmetic exception using try-catch block.


try:
    print(21/0)
except ZeroDivisionError:
    print('error: division by zero')
